### ISSUE TITLE
[Subgraph] WithSetsNumericTraits is null

### ISSUE THREAD

**Issue by froid1911** [aavegotchi/aavegotchi-matic-subgraph#101]
We have an issue with the Subgraph.
Right now some aavegotchis have the field withSetsNumericTraits is null.
This shouldnt be the case and should be the case.

``` 
{aavegotchis(where:{withSetsNumericTraits:null}) {
  id
  modifiedNumericTraits
  withSetsNumericTraits
}}
```

results in 

```
{
  "data": {
    "aavegotchis": [
      {
        "id": "14792",
        "modifiedNumericTraits": [
          79,
          22,
          2,
          3,
          53,
          71
        ],
        "withSetsNumericTraits": null
      },
      {
        "id": "1674",
        "modifiedNumericTraits": [
          77,
          8,
          8,
          32,
          85,
          11
        ],
        "withSetsNumericTraits": null
      },
      {
        "id": "20427",
        "modifiedNumericTraits": [
          44,
          56,
          20,
          29,
          78,
          50
        ],
        "withSetsNumericTraits": null
      }
    ]
  }
}
```

**Comment by orionstardust** [comment]
@froid1911 I tried to check this issue, but there's no aavegotchi whose `withSetsNumericTraits` is `null`
<img width="932" alt="Screenshot 2023-10-20 at 10 59 48 PM" src="https://github.com/aavegotchi/aavegotchi-matic-subgraph/assets/58420855/72bd2254-ebba-4449-814c-6e816ed5136a">

I tested on this.
https://subgraph.satsuma-prod.com/aavegotchi/aavegotchi-core-matic/version/v2.0.1/playground

**Comment by froid1911** [comment]
@orionstardust pls check the latest subgraph version:

https://subgraph.satsuma-prod.com/aavegotchi/aavegotchi-core-matic/version/v2.0.5/playground
