### ISSUE TITLE
Polygon Subgraph Migration

### ISSUE THREAD

**Issue by Klarue1776** [aavegotchi/aavegotchi-matic-subgraph#73]
Hello, I am a DAO member of The Graph, we'd love to chat about Polygon subgraph migration to the decentralized network, the grant program available, and prioritized co-marketing for network users. Hope to discuss all of this soon, happy to start a private chat between the teams so you have a direct line of contact 24/7.

**Comment by froid1911** [comment]
Hi Klarue, could you write me in discord? (thegraph or aavegotchi)
I'm Frank Pfeift#7456

**Comment by Klarue1776** [comment]
Absolutely. Sent you a friend request on Discord. Thanks!
